CREATE FUNCTION RESPOND_FOR_DAY (WORK_DAY DATE)
RETURNS TABLE (FNAME VARCHAR(32), LNAME VARCHAR(32))
RETURN
      SELECT FNAME,LNAME
      FROM INSTRUCTOR, RESPOND
      WHERE EGN=EGN_INSTRUCTOR AND WORK_DAY=WORK_TIME;

SELECT *
FROM TABLE (FN45267.RESPOND_FOR_DAY('06/17/2020'))T;

---------------------------------------------------------------------------------
CREATE FUNCTION COUNT_CLIENT (EGN_INSTR CHAR (10))
RETURNS TABLE (FNAME VARCHAR (32), LNAME VARCHAR(32), COUTN_CLIENT INTEGER)
RETURN
SELECT INSTRUCTOR.FNAME, INSTRUCTOR.LNAME, (SELECT COUNT(CLIENT.PHONE)
                                            FROM CLIENT
                                            WHERE INSTRUCTOR_EGN=EGN_INSTR)
FROM INSTRUCTOR
WHERE EGN=EGN_INSTR;

SELECT *
FROM  TABLE (FN45267.COUNT_CLIENT('9401266104'))T;

------------------------------------------------------------------------------------------
CREATE FUNCTION  INSTRUCTOR_TYPE (TYPE_INSTR VARCHAR(50))
RETURNS TABLE (FNAME VARCHAR(32), LNAME VARCHAR(32))
RETURN
SELECT FNAME, LNAME
FROM INSTRUCTOR
WHERE TYPE=TYPE_INSTR;

SELECT *
FROM table (FN45267.INSTRUCTOR_TYPE('Cardio'))t;

-------------------------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION  BIRTHDAY_WISH (BIRTHDAY  DATE )
RETURNS TABLE (FNAME VARCHAR(32), LNAME VARCHAR(32), PHONE CHAR(10))
RETURN
SELECT FNAME, LNAME, PHONE
FROM CLIENT
WHERE DAY(BIRHDATE)=DAY(BIRTHDAY) AND MONTH (BIRHDATE)=MONTH (BIRTHDAY)

UNION
SELECT FNAME, LNAME, PHONE
FROM INSTRUCTOR
WHERE DAY(BIRHDATE)=DAY(BIRTHDAY) AND MONTH (BIRHDATE)=MONTH (BIRTHDAY)

UNION
SELECT FNAME, LNAME, PHONE
FROM RECEPTIONIST
WHERE DAY(BIRHDATE)=DAY(BIRTHDAY) AND MONTH (BIRHDATE)=MONTH (BIRTHDAY)

UNION
SELECT FNAME, LNAME, PHONE
FROM MANAGER
WHERE DAY(BIRHDATE)=DAY(BIRTHDAY) AND MONTH (BIRHDATE)=MONTH (BIRTHDAY);


SELECT *
FROM  TABLE ( FN45267.BIRTHDAY_WISH('10/06/2021') ) T;

-----------------------------------------------------------------------------------------
CREATE FUNCTION MANAGER_STAFF(MAN_EGN CHAR(10))
RETURNS TABLE (FNAME VARCHAR(32), LNAME VARCHAR(32))
RETURN
      SELECT FNAME, LNAME
      FROM RECEPTIONIST
      WHERE MANAGER_EGN=MAN_EGN
UNION
 SELECT FNAME, LNAME
      FROM INSTRUCTOR
      WHERE MANAGER_EGN=MAN_EGN;

SELECT *
FROM  TABLE ( FN45267.MANAGER_STAFF('7412139324'))T;

-----------------------------------------------------------------------------------------------
CREATE FUNCTION SALARY_RECEPTIONIST(EGN_MANG CHAR(10))
RETURNS DECIMAL(20,2)
RETURN
     SELECT SUM (SALARY)
     FROM RECEPTIONIST
     WHERE MANAGER_EGN=EGN_MANG;


SELECT DISTINCT FN45267.SALARY_RECEPTIONIST('7412139324') AS SALARY
FROM RECEPTIONIST;

--------------------------------------------------------------------------------------------
CREATE FUNCTION SALARY_INSTRUCTOR(EGN_MANG CHAR(10))
RETURNS DECIMAL(20,2)
RETURN
     SELECT SUM (SALARY)
     FROM INSTRUCTOR
     WHERE MANAGER_EGN=EGN_MANG;

SELECT DISTINCT FN45267.SALARY_INSTRUCTOR('7412139324') AS SALARY
FROM INSTRUCTOR;
-------------------------------------------------------------------------------------------
CREATE FUNCTION COUNT_SALARY_INSTRUCTOR_UNDER(THIS_SALARY DECIMAL(10,2))
RETURNS INTEGER
RETURN
     SELECT COUNT(SALARY)
     FROM INSTRUCTOR
     WHERE SALARY< THIS_SALARY;

SELECT DISTINCT FN45267.COUNT_SALARY_INSTRUCTOR_UNDER(1000.00) AS COUNT
FROM INSTRUCTOR;
----------------------------------------------------------------------------------------------
CREATE FUNCTION COUNT_SALARY_RECEPTIONIST_UNDER(THIS_SALARY DECIMAL(10,2))
RETURNS INTEGER
RETURN
     SELECT COUNT(SALARY)
     FROM RECEPTIONIST
     WHERE SALARY< THIS_SALARY;

SELECT DISTINCT FN45267.COUNT_SALARY_RECEPTIONIST_UNDER(1000.00) AS COUNT
FROM RECEPTIONIST;

