CREATE TABLE RECEPTIONIST
( EGN CHAR(10) PRIMARY KEY  NOT NULL ,
  FNAME VARCHAR(32) NOT NULL ,
  LNAME VARCHAR(32) NOT NULL ,
  USERNAME VARCHAR(32) NOT NULL  ,
  PASSWORD VARCHAR(32) NOT NULL,
  PHONE CHAR(10) NOT NULL ,
  BIRHDATE DATE NOT NULL ,
  SALARY DECIMAL(6,2) NOT NULL,
  MANAGER_EGN CHAR(10) NOT NULL
);

CREATE TABLE MANAGER
(
 EGN CHAR(10) PRIMARY KEY NOT NULL ,
 FNAME VARCHAR(32) NOT NULL ,
 LNAME VARCHAR(32) NOT NULL ,
 PHONE CHAR(10) NOT NULL ,
 BIRHDATE DATE NOT NULL ,
 SALARY DECIMAL(6,2) NOT NULL
);



CREATE TABLE INSTRUCTOR
(
  EGN CHAR(10) PRIMARY KEY NOT NULL ,
 FNAME VARCHAR(32) NOT NULL ,
 LNAME VARCHAR(32) NOT NULL ,
 PHONE CHAR(10) NOT NULL ,
 BIRHDATE DATE NOT NULL ,
 SALARY DECIMAL(6,2) NOT NULL,
TYPE VARCHAR(50) NOT NULL,
 MANAGER_EGN CHAR (10) NOT NULL
);


CREATE TABLE CLIENT
(
 FNAME VARCHAR(32) NOT NULL ,
 LNAME VARCHAR(32) NOT NULL ,
 PHONE CHAR(10) NOT NULL PRIMARY KEY ,
 BIRHDATE DATE NOT NULL ,
 GENDER CHAR (1) NOT NULL,
 INSTRUCTOR_EGN CHAR(10)
);


CREATE  TABLE EQUIPMENT
(
    ID INTEGER PRIMARY KEY NOT NULL
     GENERATED ALWAYS AS IDENTITY
    (START WITH 1,INCREMENT BY 1),
    NAME VARCHAR(32) NOT NULL UNIQUE ,
    COUNT INTEGER
);

CREATE TABLE CARD
(
    CARD_ID INTEGER PRIMARY KEY  NOT NULL
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1,INCREMENT BY 1),
    GENDER_TYPE CHAR(1) NOT NULL ,
    PRICE DECIMAL(6,2) NOT NULL ,
    START_DATE DATE ,
    END_DATE DATE ,
    COUNT INTEGER ,
    RECEPTIONIST_EGN CHAR(10) NOT NULL,
    PHONE_CLIENT CHAR(10) NOT NULL
);


CREATE TABLE USE
(ID_EQUIPMENT INTEGER  NOT NULL ,
PHONE_CLIENT CHAR(10)  NOT NULL,
PRIMARY KEY (ID_EQUIPMENT,PHONE_CLIENT)
);

CREATE TABLE RESPOND
(
    ID_EQUIPMENT INTEGER NOT NULL ,
    EGN_INSTRUCTOR CHAR(10) NOT NULL,
    WORK_TIME DATE NOT NULL,
    PRIMARY KEY (ID_EQUIPMENT,EGN_INSTRUCTOR)
);



ALTER TABLE RECEPTIONIST ADD FOREIGN KEY (MANAGER_EGN) REFERENCES MANAGER(EGN);
ALTER TABLE INSTRUCTOR ADD FOREIGN KEY (MANAGER_EGN) REFERENCES  MANAGER(EGN);
ALTER TABLE CLIENT ADD FOREIGN KEY (INSTRUCTOR_EGN) REFERENCES INSTRUCTOR(EGN);
ALTER TABLE CARD ADD FOREIGN KEY (RECEPTIONIST_EGN) REFERENCES RECEPTIONIST(EGN);
ALTER TABLE CARD ADD FOREIGN KEY (PHONE_CLIENT) REFERENCES CLIENT(PHONE);
ALTER TABLE USE ADD FOREIGN KEY (ID_EQUIPMENT) REFERENCES EQUIPMENT(ID);
ALTER TABLE USE ADD FOREIGN KEY (PHONE_CLIENT) REFERENCES CLIENT(PHONE);
ALTER TABLE RESPOND ADD FOREIGN KEY (ID_EQUIPMENT) REFERENCES EQUIPMENT(ID);
ALTER TABLE RESPOND ADD FOREIGN KEY (EGN_INSTRUCTOR) REFERENCES INSTRUCTOR(EGN);

