CREATE TRIGGER TRIG_AFTER_INSERT_RECEPTIONIST_SALARY
    AFTER INSERT ON RECEPTIONIST
    REFERENCING NEW AS N
    FOR EACH ROW
        UPDATE RECEPTIONIST
        SET SALARY=610
    WHERE EGN=N.EGN AND SALARY < 610;

CREATE OR REPLACE TRIGGER TRIG_BEFORE_UPDATE_RECEPTIONIST_SALARY
 BEFORE UPDATE ON RECEPTIONIST
      REFERENCING NEW AS N
    FOR EACH ROW
      WHEN (N.SALARY <610 AND EGN=N.EGN)
      SET N.SALARY=610;


CREATE TRIGGER TRIG_AFTER_INSERT_MANAGER_SALARY
    AFTER INSERT ON MANAGER
    REFERENCING NEW AS N
    FOR EACH ROW
        UPDATE MANAGER
        SET SALARY=610
    WHERE EGN=N.EGN AND SALARY < 610;


CREATE OR REPLACE TRIGGER TRIG_BEFORE_UPDATE_MANAGER_SALARY
 BEFORE UPDATE ON MANAGER
      REFERENCING NEW AS N
    FOR EACH ROW
      WHEN (N.SALARY <610 AND EGN=N.EGN)
      SET N.SALARY=610;


CREATE TRIGGER TRIG_AFTER_INSERT_INSTRUCTOR_SALARY
    AFTER INSERT ON INSTRUCTOR
    REFERENCING NEW AS N
    FOR EACH ROW
        UPDATE INSTRUCTOR
        SET SALARY=610
    WHERE EGN=N.EGN AND SALARY < 610;

CREATE OR REPLACE TRIGGER TRIG_BEFORE_UPDATE_INSTRUCTOR_SALARY
 BEFORE UPDATE ON INSTRUCTOR
      REFERENCING NEW AS N
    FOR EACH ROW
      WHEN (N.SALARY <610 AND EGN=N.EGN)
      SET N.SALARY=610;



CREATE TRIGGER TRIG_BEFORE_UPDATE_CARD_PRICE_PERIOD_AND_GENDER_F
 BEFORE UPDATE ON CARD
      REFERENCING NEW AS N
    FOR EACH ROW
      WHEN (N.PRICE <23 AND CARD_ID=N.CARD_ID AND GENDER_TYPE='F' AND START_DATE IS NOT NULL AND END_DATE IS NOT NULL)
      SET N.PRICE=23;

CREATE TRIGGER TRIG_BEFORE_UPDATE_CARD_PRICE_PERIOD_AND_GENDER_M
 BEFORE UPDATE ON CARD
      REFERENCING NEW AS N
    FOR EACH ROW
      WHEN (N.PRICE <33 AND CARD_ID=N.CARD_ID AND GENDER_TYPE='M' AND START_DATE IS NOT NULL AND END_DATE IS NOT NULL)
      SET N.PRICE=33;

CREATE TRIGGER TRIG_AFTER_INSERT_CARD_PRICE_PERIOD_AND_GENDER_F
    AFTER INSERT ON CARD
    REFERENCING NEW AS N
    FOR EACH ROW
        UPDATE CARD
        SET PRICE=23
    WHERE CARD_ID=N.CARD_ID AND PRICE < 23 AND GENDER_TYPE='F' AND START_DATE IS NOT NULL AND END_DATE IS NOT NULL;

CREATE TRIGGER TRIG_AFTER_INSERT_CARD_PRICE_PERIOD_AND_GENDER_M
    AFTER INSERT ON CARD
    REFERENCING NEW AS N
    FOR EACH ROW
        UPDATE CARD
        SET PRICE=33
    WHERE CARD_ID=N.CARD_ID AND PRICE < 33 AND GENDER_TYPE='M' AND START_DATE IS NOT NULL AND END_DATE IS NOT NULL;